### ISSUE TITLE
Integrate JMETER+ICAP image with test data

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/p-k8-jmeter-test-engine#11]

**Comment by MaNe2020** [comment]
https://github.com/k8-proxy/k8-performance-use-cases/issues/19

**Comment by dpatel7** [comment]
@MaNe2020 Having some issue while running docker-compose up 
![image](https://user-images.githubusercontent.com/61416876/94279014-7344c580-ff43-11ea-8461-0a6b00b0c090.png)

**Comment by MaNe2020** [comment]
@dpatel7 can you try replacing docker-compose.yaml with the one I'll sent you on slack.

**Comment by dpatel7** [comment]
@MaNe2020 Look like requirements.txt missing or not in same path. 
![image](https://user-images.githubusercontent.com/61416876/94406207-905add80-0169-11eb-8120-62bda2b0ac1e.png)

**Comment by dpatel7** [comment]
@MaNe2020 Please advise as soon as you can run the input file from minio

**Comment by dpatel7** [comment]
@MaNe2020 i can't run the solution from my machine due to wsl issue. i have manage to run @ggrig solution and manage to deploy the pod but i would like to know where we can update thread numbers to get more load from single pod

**Comment by dpatel7** [comment]
@MaNe2020 can you update your JMX script to use concurrency thread group and update any dependency to docker file
