### ISSUE TITLE
Optimize k8 jmeter script move files to in and out folders i.e remove python background script dependancy

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#116]
in k8 jmeter script they are using external python script to move files from minio to local

We are assuming that minio supports full aws s3 sdk. task would be to try exact same approach used in aws jmeter script in k8 jmeter script

with external python script downloading files, we dont have control of output. at least out is not validated currently

**Comment by MaNe2020** [comment]
@uzfarid change is required to this script: ICAP-POC_s3_k8.jmx?

**Comment by uzfarid** [comment]
yes

**Comment by MaNe2020** [comment]
@uzfarid why this needs to be uploaded into minio? 
If AWS SDK jars (along with few others) are added into JMeter, it can be directly downloaded/uploaded (http://doloadtest.blogspot.com/2018/04/upload-download-from-aws-s3-via-jmeter.html)
Let me know what do you think about solution from this link?

**Comment by uzfarid** [comment]
Because aim is that this solution should not be dependant on s3. It should
be possible to run it from anywhere. Minio can be setup in persons local
machine and but we cannot have s3 in persons local machine
