### ISSUE TITLE
Integrating minio for input test files

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/p-k8-jmeter-test-engine#12]

**Comment by uzfarid** [comment]
@MaNe2020 , any status on this plz?

**Comment by MaNe2020** [comment]
@uzfarid PR for this is already created. And there is still PR#29 with most recent changes.
Concept of pulling files via py script is used. The only thing left was to integrate some external storage since, local minio is used. 
There is also a video that shows the work done: https://www.loom.com/share/681101e348484316a94658ce192a467e
Please let me know if anything else is needed here.

**Comment by uzfarid** [comment]
@MaNe2020 can u create pull request plz?
