### ISSUE TITLE
Update minio dependency in current docker file. 

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#143]
## Using MinIO
Script ICAP_POC_Minio.jmx is removing python script (upload.py and download.py) dependency from ICAP_POC_s3_k8.jmx script.
It uses minio-7.1.4.jar that should be imported from Maven into JMeter lib folder.
It executes upload and download based on MinIO API directly as part of JSR232Sampler.
In case docker image needs to be changed, following just add:
 - cd /path/to/jmeter/lin
 - wget https://repo1.maven.org/maven2/io/minio/minio/7.1.4/minio-7.1.4-all.jar

https://github.com/k8-proxy/p-k8-jmeter-test-engine/pull/141

**Comment by dpatel7** [comment]
@ggrig if you need any assistance speak to Maria or Farid

**Comment by ggrig** [comment]
I do not find ICAP_POC_Minio.jmx in the repo.
Where is the script located?

**Comment by dpatel7** [comment]
@ggrig Farid made updated version of AWS and maria's script in src/controller/docker-jmeter-c-icap/ICAP_Direct_FileProcessing_k8_v1.jmx 
Use that please.

**Comment by dpatel7** [comment]
I have merger couple of PR so please make pull request.
