### ISSUE TITLE
Health check monitoring of the icap-server

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine#15]
Provide the heatlh check monitoring of the icap-server using the output of the c-icap-client

```
Metrics to monitor:
➢ Running Servers Statistics
• Children number:
• Free Servers:
• Used Servers:
• Started Processes:
• Closed Processes:
• Crashed Processes:
• Closing Processes:
➢ Service gw_rebuild Statistics
• Service gw_rebuild REQMODS:
• Service gw_rebuild RESPMODS:
• Service gw_rebuild REQUESTS SCANNED:
• Service gw_rebuild REBUILD FAILURES:
• Service gw_rebuild REBUILD ERRORS:
• Service gw_rebuild SCAN REBUILT:
• Service gw_rebuild UNPROCESSED:
• Service gw_rebuild UNPROCESSABLE:
• Service gw_rebuild BYTES IN:
• Service gw_rebuild BYTES OUT:
• Service gw_rebuild HTTP BYTES IN:
• Service gw_rebuild HTTP BYTES OUT:
• Service gw_rebuild BODY BYTES IN:
• Service gw_rebuild BODY BYTES OUT:
• Service gw_rebuild BODY BYTES SCANNED:
```

**Comment by hongson1981** [comment]
@faisaladnanpeltops @dpatel7 
I will work on this as discussing in the meeting

**Comment by hongson1981** [comment]
@dpatel7 
Update my solution :
First, Create JRS223 PreProcesser to : 
1. Run command "/usr/local/c-icap/bin/c-icap-client -s info?view=text -i gw-icap01.westeurope.azurecontainer.io -req any" to get ICAP server metrics
2. Convert ICAP server metrics from text to  InfluxDB line protocol syntax like this  
   Running Servers Statistics 20201007184538 ....
   General Statistics Children number=3,Free Servers=26,Used Servers=4  ...
   Service info Statistics REQUESTS=705,REQMODS=6, ....
   Service echo Statistics Service info REQMODS=6,Service info RESPMODS=0,....
   Service gw_rebuild Statistics Service echo REQMODS=0,Service echo RESPMODS=0,..
each line is one measurement
3. Put all measurements to variable ${icap_measurements}

Second, Create http sampler to post  ${icap_measurements} to influxDB server
Third, Using Grafana to present icap_measurement on Dashboard
Currently, I am working on .2 Convert ICAP server metrics from text to  InfluxDB line protocol syntax,

**Comment by uzfarid** [comment]
@hongson1981  running in preprocessor is not ideal solution. i guess u want to include as preprocessor step for before this request?

Ideal and simpler approach is to create new thread group with 1 user and run duration should be exact same as actual jmeter script. and run is normal JRS223 Sampler.

**Comment by hongson1981** [comment]
@dpatel7 @uzfarid 
I fetched ICAP server metrics to InfluxDB, Now, I am investigating how to present them on Grafana dashboard.

**Comment by hongson1981** [comment]
@uzfarid 
I update jmeter script to work with parameters, I temporary push to my git via link below :
https://github.com/hongson1981/p-k8-jmeter-test-engine-v1/tree/master/upwork-devs/Son-Ha
