### ISSUE TITLE
Create master that create dashboard and also "stack" 

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#158]
this is continuation of https://github.com/k8-proxy/p-k8-jmeter-test-engine/pull/157 this and aim is to have similar kind of master script as in aws jmeter engine project

**Comment by Ali-J2** [comment]
This should be done, see PR 180

https://github.com/k8-proxy/p-k8-jmeter-test-engine/pull/180
