### ISSUE TITLE
Implement direct grafana and minio connection capability and access control should be via IP list

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#173]

**Comment by shashanksinha89** [comment]
Both grafana and minio are exposed. Only accessible to specific IP.

**Comment by uzfarid** [comment]
should be both AWS & Azure

**Comment by shashanksinha89** [comment]
Applied the solution to both AWS & Azure

**Comment by dpatel7** [comment]
@shashanksinha89 can we create read me how to add anyone to white IP list?

**Comment by shashanksinha89** [comment]
#188
