### ISSUE TITLE
Integrating Latest Jmeter Image to work with test engine

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#19]

**Comment by dpatel7** [comment]
Manage to run custom image using test engine but can only see 1 single file in output. and is corrupt
![image](https://user-images.githubusercontent.com/61416876/94682858-7feb6400-031d-11eb-9590-4a65704ac7d9.png) @ggrig can you please have a look with running more then one thread in your existing docker image

**Comment by dpatel7** [comment]
@ggrig Please integrate maria's latest script in current test engine

**Comment by dpatel7** [comment]
@ggrig Please try and utilize script from AWS test engine.

**Comment by faisaladnanpeltops** [comment]
Action point:
Update the Javascript in the JMX file to
- read input files from local directory in the docker
- write output files to minio
ETA: tomorrow, best effort today.
