### ISSUE TITLE
Impliment Master Stack_dash_creation script to update number of pods value to dashboard

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#192]

**Comment by dpatel7** [comment]
still can't see number of pods value added in dashboard

**Comment by uzfarid** [comment]
@dpatel7 could you please specify what you need here with some examples.

**Comment by dpatel7** [comment]
@Ali-J2 Is look like the Math is not getting added as per number of pods running.
