### ISSUE TITLE
Create Custom Helm chart for loki deployment 

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#194]
When try to install using standard Helm chart seen below error - 

helm upgrade --install promtail --namespace=common loki/promtail --set "loki.serviceName=loki"
Release "promtail" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "promtail" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "common": current value is "loki-stack"

**Comment by shashanksinha89** [comment]
#229
