### ISSUE TITLE
Create environment, logging and visualisation system

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine#2]
Create scripts that does the following:
1. Deploy Elasticsearch
2. Deploy Logstash
3. Deploy Kibana
4. Deploy Prometheus
5. Deploy Grafana -- prio
6. Deploy InfluxDB -- prio

There are 2 kind of scripts:
1. docker compose for local development
2. k8s manifest for staging and production environments

**Comment by faisaladnanpeltops** [comment]
this is for roozbeh

**Comment by dpatel7** [comment]
@upworkroozbeh Please update your progress here

**Comment by uzfarid** [comment]
@upworkroozbeh is this kind of done or what is status of this? not clear from statuses.

**Comment by upworkroozbeh** [comment]
> @upworkroozbeh is this kind of done or what is status of this? not clear from statuses.

This is done 
I was asked to clear log files so I did 
It's done now
