### ISSUE TITLE
Create single OVA with common resources and load generator

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#203]
Single OVA should contain kubernetes cluster with:

Common Resources: 
- influx db pod
- grafana pod
- loki pod
- prometheious pod
- promtail pod
- minio pod

Load Generator:
- Jmeter pod (25 users)

- test data

@ggrig We can use this issue to Track any more update to OVA Task.

- [ ] Configure Static IP for OVA

- [ ] Merger New image change to OVA

**Comment by dpatel7** [comment]
@ggrig We can use this issue to Track any more update to OVA Task.

- [ ] Configure Static IP for OVA

- [ ] Merger New image change to OVA

**Comment by uzfarid** [comment]
@ggrig what else we need to work on here?
