### ISSUE TITLE
CSV file should be passed directly without use secrets.

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#207]

**Comment by dpatel7** [comment]
The Current limitation is 3MB file which is the biggest size you can pass it to PODs. Need to take alternative approach to pass large CSV files to pods

**Comment by ggrig** [comment]
Hi @Dharam Patel (Glasswall Solutions- Test Analyst) 
Got a question concerning the implementation of https://github.com/k8-proxy/p-k8-jmeter-test-engine/issues/207. 
The approach you proposed with https://stackoverflow.com/questions/54181419/make-large-static-data-files-available-to-kubernetes-pods allows attaching files which are publicly available with HTTP/HTTPS. 
On the other hand, you mentioned that the file should be placed on a Minio server. Minio does not provide direct access to files with HTTP/HTTPS.
My question is - are we going to place the CSV files to minio servers only, or those may be placed on other servers accessible over HTTP/HTTPS?

**Comment by ggrig** [comment]
The decision here is to utilize file lists we have on GitHub. So no Minio downloads and files will be downloaded to the PODs during POD init with HTTP/HTTPS

**Comment by uzfarid** [comment]
let's go also with minio  i.e upload to minio and download from minio. good to check logic we use in AWS side to differentiate different runs with different files.
