### ISSUE TITLE
Modify create_stack_dash.py to accept jmx script and ICAP port as parameter

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#208]

**Comment by dpatel7** [comment]
still can't pass jmx from run time

**Comment by ggrig** [comment]
Hi Dharam,
It has been agreed that it was mainly about switching to JMX file version 3 and also about adding TLS switches there.
JMX file must have a number of parameters like number_of_threads, duration_in_seconds, minio_endpoint, minio_access_key, minio_secret_key, etc. So, we cannot pass an arbitrary JMX file to the script.
Can you please describe the use cases for the request?
