### ISSUE TITLE
Create Docker image to run test UI from k8

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#219]
Install Angular dependency
Install Flask Server
Install Kubectl
Provide Access to Cluster to Trigger the Test
Utilize user input from UI to replace config value as below.

AWS_PROFILE_NAME=
REGION=
TOTAL_USERS=
USERS_PER_INSTANCE=
DURATION=
TEST_DATA_FILE=
MINIO_EXTERNAL_URL=
MINIO_URL=
MINIO_ACCESS_KEY=
MINIO_SECRET_KEY=
MINIO_INPUT_BUCKET=
MINIO_OUTPUT_BUCKET=
INFLUXDB_URL=
PREFIX=
ICAP_SERVER_URL=
GRAFANA_URL=
GRAFANA_API_KEY=
GRAFANA_SECRET=
GRAFANA_FILE=
EXCLUDE_DASHBOARD=
PRESERVE_STACK=
ICAP_SERVER_PORT=
ENABLE_TLS=
TLS_VERIFICATION_METHOD=
JMX_FILE_PATH=
PROXY_STATIC_IP=
LOAD_TYPE=

All above will be packed in Docker Image ( For Providing Access to Cluster need to discuss best possible way which is best for security)

**Comment by uzfarid** [comment]
it is still ongoing
