### ISSUE TITLE
OVA release automation

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#230]

**Comment by dpatel7** [comment]
Utilizing Packer

**Comment by shashanksinha89** [comment]
#318

**Comment by ggrig** [comment]
@dpatel7 
According to @shashanksinha89 you should configure the AWS credentials to be used by the packer-build action.
Seems that the steps are described at https://github.com/aws-actions/configure-aws-credentials
