### ISSUE TITLE
Utilize existing Health check in OVA after latest changes deployed

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#287]
UI should be up
latest changes in place
microk8s is running
common resource are running
script to very generate load and grafana graphs.

**Comment by ggrig** [comment]
A question here:
Does "...latest changes deployed..." mean the latest changes from github?

**Comment by dpatel7** [comment]
> A question here:
> Does "...latest changes deployed..." mean the latest changes from GitHub?
> Or does it have a different meaning?

Yes, it mean we have updated repo
