### ISSUE TITLE
Need Price estimation to run test with different scenario in Azure k8 to start with

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#40]
What we need is different prices to run smallest to largest nodes. and need what will be the cost to run 100k user test.

**Comment by dpatel7** [comment]
https://azure.microsoft.com/en-gb/pricing/calculator/

**Comment by dpatel7** [comment]
| K8 Engine Cost Estimation          |          |           |        |                |                         |      |
|------------------------------------|----------|-----------|--------|----------------|-------------------------|------|
| Current K8 Capacity                |          |           |        |                |                         |      |
| Resource                           | Quantity | vCPU/node | Memory | Total requests | Max Concurrent Requests | Cost |
| Cluster                            | 1        |           |        |                |                         |      |
| Nodes                              | 3        |           |        |                |                         |      |
| Pods in a node                     | 6        |           |        |                |                         |      |
| Total Pods                         | 18       |           |        |                |                         |      |
|                                    |          |           |        |                |                         |      |
|                                    |          |           |        |                |                         |      |
|                                    |          |           |        |                |                         |      |
| Estimated K8 Capacity Requirements |          |           |        |                |                         |      |
| Resource                           | Quantity | vCPU/node | Memory | Total requests | Max Concurrent Requests | Cost |
| Cluster                            | 1        |           |        |                |                         |      |
| Nodes                              | 3        |           |        |                |                         |      |
| Pods in a node                     | 6        |           |        |                |                         |      |
| Total Pods                         | 18       |           |        |                |                         |      |

**Comment by dpatel7** [comment]
@pranaysahith use above format for cost estimation

**Comment by pranaysahith** [comment]
@dpatel7 I have created a very similar cost estimator in PR #48 
Please review and lets discuss about it
