### ISSUE TITLE
Work on JVM to specify resource to jmeter 

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#56]
@ggrig Try and pass it as parameter. 

set -e
freeMem=`awk '/MemFree/ { print int($2/1024) }' /proc/meminfo`
s=$(($freeMem/10*8))
x=$(($freeMem/10*8))
n=$(($freeMem/10*2))
export JVM_ARGS="-Xmn${n}m -Xms${s}m -Xmx${x}m"

**Comment by ggrig** [comment]
Some tips at https://www.blazemeter.com/blog/9-easy-solutions-jmeter-load-test-%E2%80%9Cout-memory%E2%80%9D-failure

**Comment by ggrig** [comment]
Another task to be performed here

**Comment by ggrig** [comment]
Closed after the PR #71 merged
