### ISSUE TITLE
Create dashboard using Grafana and Influx DB

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/p-k8-jmeter-test-engine#6]
1. CPU & Memory utilisation of the running pods
2. Number of files processed
3. Number of concurrent requests processed
4. Error/Success call
5.

**Comment by faisaladnanpeltops** [comment]
this is for susanta

**Comment by hongson1981** [comment]
I can handle this task if no one else working on it

**Comment by dpatel7** [comment]
@hongson1981 any progress on this?

**Comment by hongson1981** [comment]
@dpatel7 
using Grafana and Prometheus to monitor Pod/node health ( CPU/RAM/Status...) and Jmeter test result

**Comment by hongson1981** [comment]
@dpatel7 @pranaysahith 
I see that we can also use Grafana to monitor Pod/node health based on Prometheus DB which is also installed already
[kubernetes-pod-overview_rev4.zip](https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/files/5318346/kubernetes-pod-overview_rev4.zip)

**Comment by dpatel7** [comment]
@hongson1981 Please use that and Implement it

**Comment by hongson1981** [comment]
Hi @dpatel7 , @faisaladnanpeltops 
Please see instruction via attached file to deploy Grafana, Prometheus and InfluxDB to monitor Pods health and Jmeter test result

[Grafana_Prometheus+InfluxDB on Kubernetes.zip](https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/files/5321781/Grafana_Prometheus%2BInfluxDB.on.Kubernetes.zip)
