### ISSUE TITLE
unable to recognize "elk/tenant_multipod.yaml": no matches for kind...

### ISSUE THREAD

**Issue by MariuszFerdyn** [k8-proxy/p-k8-jmeter-test-engine#70]
cd p-k8-jmeter-test-engine/kubernetes/common_resources
kubectl apply -n elk -f elk/tenant_multipod.yaml
unable to recognize "elk/tenant_multipod.yaml": no matches for kind "Elasticsearch" in version "elasticsearch.k8s.elastic.co/v1"
unable to recognize "elk/tenant_multipod.yaml": no matches for kind "Kibana" in version "kibana.k8s.elastic.co/v1"
unable to recognize "elk/tenant_multipod.yaml": no matches for kind "Beat" in version "beat.k8s.elastic.co/v1beta1"

**Comment by uzfarid** [comment]
elk pods not needed
