### ISSUE TITLE
Define approach to split pods for common resources and actual load generators

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#75]
There are 2 category of pods in jmeter k8 project

- category 1: common resources pods: influxdb, grafana, minio,promethous https://github.com/k8-proxy/p-k8-jmeter-test-engine/tree/master/kubernetes/common_resources (ignore elk folder here)

- category 2: jmeter load generator pods

Basically, in category 1 node pool, we need to ensure that no category 2 pods are running there and vice versa i.e in category 2 node pool, we need to ensure no category 1 pods are running

Main aim of this task to define how this kind of separation can be achieved in k8 azure and document instructions

**Comment by MariuszFerdyn** [comment]
Fast solution:

kubectl taint node firstpool key=firstpool:NoSchedule


firstpool from now will not be participated in new pod creation.

**Comment by MariuszFerdyn** [comment]
Fast solution for node pool:

az aks nodepool update  \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name firstpool \
    --node-taints sku=firstpool:NoSchedule

firstpool node pool from now will not be participated in new pod creation.

**Comment by MariuszFerdyn** [comment]
How to create a New AKS Node Pool Dedicated to the JMETER - example (https://glasswallsolu-qbp1117.slack.com/archives/C01B8TNJ3EF/p1603144798015900) - Will be included in AKS creation:

az login
az aks list -o table
$RESOURCEGROUPNAME="k8s"
$AKS_NAME="k8s"
az aks nodepool add --resource-group $RESOURCEGROUPNAME --cluster-name $AKS_NAME --name jmeter --node-count 1 --node-taints sku=jmeter:NoSchedule
kubectl create -f phpinfo.yaml


phpinfo.yaml:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-info
  template:
    metadata:
      labels:
        app: php-info
    spec:
      containers:
      - name: php-info
        image: jasoncallaway/phpinfo
        resources: {}
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "jmeter"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: php-info
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  selector:
    app: php-info

**Comment by uzfarid** [comment]
@MariuszFerdyn plz make pull request before u close ticket.

**Comment by dpatel7** [comment]
@MariuszFerdyn can you please update command so we can specify node size before adding to cluster
