### ISSUE TITLE
Investigate errors occurring when running tests

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/p-k8-jmeter-test-engine#98]
Errors are seen from the point where the number of users is ramping down which may be a issue with the test tool.
See attached

![image](https://user-images.githubusercontent.com/61200359/97020037-f9572a80-1548-11eb-8f25-62770c848351.png)

**Comment by uzfarid** [comment]
@NadHodeGW is it possible to include some entries from jmeter.log file plz?
